version: "3.2"

services:
  # Usage: `docker-compose build ul`
  ul:
    # TODO: Change this later
#    image: ul-website-dev:latest
    depends_on:
      - couchdb-lucene
      - couchdb
    ports:
      - "4896:4896"
    environment:
    - NODE_ENV=production
    volumes:
      - type: bind
        source: /srv/ul-images
        target: /srv/ul-images
      - type: bind
        source: /srv/ul-updates-reports
        target: /srv/ul-updates-reports
    build:
      context: .
      dockerfile: Dockerfile

  # This must use this alias in order for couchdb-lucene to use it with its default options.
  couchdb:
    image: couchdb:2.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - type: bind
        source: /srv/docker-couchdb_data
        target: /opt/couchdb/data

  couchdb-lucene:
    image: klaemo/couchdb-lucene:2.1.0
    ports:
      - "5985:5985"
    depends_on:
      - couchdb
    # Not used, we are currently just using the container's storage itself and not retaining indices between runs.
    # volumes:
    #   - type: bind
    #     source: /srv/docker-couchdblucene_indexes
    #     target: /opt/couchdb-lucene/indexes
